#!/usr/bin/env python

SPOTIPY_CLIENT_ID = "SPOTIPY_CLIENT_ID"
SPOTIPY_CLIENT_SECRET = "SPOTIPY_CLIENT_SECRET"
GENIUS_CLIENT_TOKEN = "GENIUS_CLIENT_TOKEN"
TEXT_ANALYTICS_KEY = "TEXT_ANALYTICS_KEY"
TEXT_ANALYTICS_ENDPOINT = "TEXT_ANALYTICS_ENDPOINT"
LOCAL_FILE_STORE_PATH = "src/store/"
LOCAL_FILE_STORE_NAME = "lyrics.json"
